const TYPES = {

    LOGIN:"[AUTH] LOGIN",
    LOGOUT:"[AUTH] LOGOUT",

    UISETERROR:"[UI] SET ERROR",
    UIREMOVEERROR:"[UI] UIREMOVEERROR",

    UISTARTLOADING:"[UI] START LOADING",
    UIFINISHLOADING:"[UI] FINISH LOADING"

}
export default TYPES